-- ============================================================
-- SESSIONS — Marketplace Jasa Web & Produk
-- Skema database (PostgreSQL 15+ / Supabase)
--
-- Cara pakai:
--   1. Via migrasi (disarankan, idempotent):
--        php database/migrate.php
--   2. Atau manual di Supabase Dashboard > SQL Editor:
--        jalankan seluruh file ini
--
-- CATATAN timezone: kolom timestamp menyimpan waktu LOKAL (WIB, +07).
-- Sesi Postgres di-set 'Asia/Jakarta' oleh database.php. Jangan diubah
-- ke UTC atau setiap baris baru akan tersimpan 7 jam di belakang baris lama.
-- ============================================================

-- ── Fungsi & trigger pembarui timestamp ───────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ── Pengguna ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL DEFAULT '',
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(255) NOT NULL,          -- hash password_hash(), bukan plaintext
    phone       VARCHAR(25)  NULL,
    location    VARCHAR(100) NULL,
    avatar      VARCHAR(255) NULL,
    role        TEXT NOT NULL DEFAULT 'buyer'
                CHECK (role IN ('buyer','seller','admin')),
    status      TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active','inactive')),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NULL,
    email       VARCHAR(100) NOT NULL
);
-- CATATAN: tidak ada UNIQUE pada email. Data lama punya 15 email kosong dan
-- 2 duplikat; menambah UNIQUE akan gagal sampai data dibersihkan.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username);

-- ── Kategori ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(60) NOT NULL,
    slug        VARCHAR(60) NOT NULL,
    type        TEXT NOT NULL DEFAULT 'all'
                CHECK (type IN ('product','service','all')),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cat_slug UNIQUE (slug)
);

-- ── Subtipe & merek (atribut terstruktur listing) ─────────────
CREATE TABLE IF NOT EXISTS listing_subtypes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    name        VARCHAR(60) NOT NULL,
    slug        VARCHAR(60) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subtype_cat UNIQUE (category_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_subtype_cat ON listing_subtypes (category_id);

CREATE TABLE IF NOT EXISTS listing_brands (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtype_id  INTEGER NOT NULL REFERENCES listing_subtypes(id) ON DELETE CASCADE,
    name        VARCHAR(60) NOT NULL,
    slug        VARCHAR(60) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_brand_subtype UNIQUE (subtype_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_brand_subtype ON listing_brands (subtype_id);

-- ── Profil toko (multi-seller, menunggu approval admin) ──────
CREATE TABLE IF NOT EXISTS seller_profiles (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    store_name    VARCHAR(100) NOT NULL,
    store_desc    TEXT NULL,
    payout_info   VARCHAR(100) NULL,   -- rekening / e-wallet pencairan
    home_address  TEXT NULL,          -- alamat rumah (HANYA tampil utk admin)
    approval      TEXT NOT NULL DEFAULT 'pending'
                  CHECK (approval IN ('pending','approved','rejected')),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_seller_user UNIQUE (user_id),
    CONSTRAINT fk_seller_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
DROP TRIGGER IF EXISTS seller_profiles_set_updated_at ON seller_profiles;
CREATE TRIGGER seller_profiles_set_updated_at BEFORE UPDATE ON seller_profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Brief custom (buyer minta penawaran jasa) ────────────────
CREATE TABLE IF NOT EXISTS briefs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id      INTEGER NOT NULL,
    seller_id     INTEGER NULL,       -- diarahkan ke seller tertentu (opsional)
    title         VARCHAR(150) NOT NULL,
    requirements  TEXT NOT NULL,
    budget_min    NUMERIC NULL,
    budget_max    NUMERIC NULL,
    deadline      DATE NULL,
    quote_price   NUMERIC NULL,       -- penawaran harga dari seller
    status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','quoted','accepted','rejected','closed')),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_brief_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_brief_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_brief_buyer ON briefs (buyer_id);
CREATE INDEX IF NOT EXISTS idx_brief_seller ON briefs (seller_id);
DROP TRIGGER IF EXISTS briefs_set_updated_at ON briefs;
CREATE TRIGGER briefs_set_updated_at BEFORE UPDATE ON briefs
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Listing (jasa ATAU produk — kolom type) ───────────────────
CREATE TABLE IF NOT EXISTS listings (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    INTEGER NOT NULL,
    category_id  INTEGER NULL,
    subtype_id   INTEGER NULL,      -- tipe produk dalam kategori (mis. Motor)
    brand_id     INTEGER NULL,      -- merek subtipe (mis. Honda), opsional
    type         TEXT NOT NULL DEFAULT 'product'
                 CHECK (type IN ('product','service')),
    title        VARCHAR(150) NOT NULL,
    description  TEXT NOT NULL,
    price        NUMERIC NOT NULL DEFAULT 0,   -- harga dasar / mulai
    condition    TEXT NULL          -- produk saja
                 CHECK (condition IN ('baru','seperti-baru','bekas-baik','bekas-cukup')),
    location     VARCHAR(100) NULL,
    province     VARCHAR(100) NULL,  -- cascade wilayah: nama provinsi
    regency      VARCHAR(100) NULL,  -- nama kabupaten / kota
    district     VARCHAR(100) NULL,  -- nama kecamatan
    rt           VARCHAR(10)  NULL,  -- RT (disimpan, tidak dipublikasikan)
    rw           VARCHAR(10)  NULL,  -- RW (disimpan, tidak dipublikasikan)
    website      VARCHAR(255) NULL,  -- link demo/portofolio (jasa)
    stack        VARCHAR(255) NULL,  -- teknologi (jasa)
    status       TEXT NOT NULL DEFAULT 'available'
                 CHECK (status IN ('available','sold','inactive')),
    moderation   TEXT NOT NULL DEFAULT 'pending'
                 CHECK (moderation IN ('pending','approved','rejected')),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_listing_seller  FOREIGN KEY (seller_id)   REFERENCES users(id)            ON DELETE CASCADE,
    CONSTRAINT fk_listing_cat     FOREIGN KEY (category_id) REFERENCES categories(id)       ON DELETE SET NULL,
    CONSTRAINT fk_listing_subtype FOREIGN KEY (subtype_id)  REFERENCES listing_subtypes(id) ON DELETE SET NULL,
    CONSTRAINT fk_listing_brand   FOREIGN KEY (brand_id)    REFERENCES listing_brands(id)   ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_listing_seller  ON listings (seller_id);
CREATE INDEX IF NOT EXISTS idx_listing_cat     ON listings (category_id);
CREATE INDEX IF NOT EXISTS idx_listing_subtype ON listings (subtype_id);
CREATE INDEX IF NOT EXISTS idx_listing_brand   ON listings (brand_id);
CREATE INDEX IF NOT EXISTS idx_listing_browse  ON listings (moderation, status, created_at);
DROP TRIGGER IF EXISTS listings_set_updated_at ON listings;
CREATE TRIGGER listings_set_updated_at BEFORE UPDATE ON listings
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Foto listing ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS listing_images (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    image_url   VARCHAR(255) NOT NULL,
    is_primary  BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_img_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS fk_img_listing ON listing_images (listing_id);

-- ── Paket harga listing (Basic / Pro / Enterprise) ───────────
CREATE TABLE IF NOT EXISTS listing_packages (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id    INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    name          VARCHAR(60) NOT NULL,
    price         NUMERIC NOT NULL,
    duration_days INTEGER NULL,     -- estimasi pengerjaan
    revisions     INTEGER NULL,     -- jumlah revisi
    features      TEXT NULL,        -- daftar fitur (satu per baris)
    sort_order    SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pkg_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS fk_pkg_listing ON listing_packages (listing_id);

-- ── Pesanan (transaksi manual: bayar → upload bukti → verifikasi) ──
CREATE TABLE IF NOT EXISTS orders (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code        VARCHAR(20) NOT NULL,
    buyer_id          INTEGER NOT NULL,
    seller_id         INTEGER NOT NULL,
    listing_id        INTEGER NULL,
    package_id        INTEGER NULL,
    brief_id          INTEGER NULL,
    title             VARCHAR(150) NOT NULL,   -- snapshot judul yang dibeli
    total             NUMERIC NOT NULL,
    payment_method    VARCHAR(20) NULL,       -- QRIS / DANA / BCA / ...
    payment_proof     VARCHAR(255) NULL,       -- file upload bukti bayar
    shipping_address  TEXT NULL,               -- alamat (produk fisik)
    status            TEXT NOT NULL DEFAULT 'menunggu_bukti'
                      CHECK (status IN ('menunggu_bukti','diverifikasi','proses','selesai','batal')),
    notes             TEXT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_code UNIQUE (order_code),
    CONSTRAINT fk_order_buyer   FOREIGN KEY (buyer_id)   REFERENCES users(id)            ON DELETE CASCADE,
    CONSTRAINT fk_order_seller  FOREIGN KEY (seller_id)  REFERENCES users(id)            ON DELETE CASCADE,
    CONSTRAINT fk_order_listing FOREIGN KEY (listing_id) REFERENCES listings(id)         ON DELETE SET NULL,
    CONSTRAINT fk_order_package FOREIGN KEY (package_id) REFERENCES listing_packages(id) ON DELETE SET NULL,
    CONSTRAINT fk_order_brief   FOREIGN KEY (brief_id)   REFERENCES briefs(id)           ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_order_buyer ON orders (buyer_id);
CREATE INDEX IF NOT EXISTS idx_order_seller ON orders (seller_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON orders (status);
CREATE INDEX IF NOT EXISTS fk_order_listing ON orders (listing_id);
CREATE INDEX IF NOT EXISTS fk_order_package ON orders (package_id);
CREATE INDEX IF NOT EXISTS fk_order_brief ON orders (brief_id);
DROP TRIGGER IF EXISTS orders_set_updated_at ON orders;
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Ulasan (1 order = 1 review, hanya setelah selesai) ───────
CREATE TABLE IF NOT EXISTS reviews (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    buyer_id         INTEGER NOT NULL,
    seller_id        INTEGER NOT NULL,
    listing_id       INTEGER NULL,
    rating           SMALLINT NOT NULL,      -- 1..5
    comment          TEXT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NULL,         -- buyer mengedit ulasan (label "diedit")
    reply            TEXT NULL,              -- balasan penjual
    replied_at       TIMESTAMP NULL,
    reply_updated_at TIMESTAMP NULL,
    CONSTRAINT uq_review_order UNIQUE (order_id)
);

-- ── Favorit ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS favorites (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fav UNIQUE (user_id, listing_id)
);
CREATE INDEX IF NOT EXISTS idx_fav_listing ON favorites (listing_id);

-- ── Laporan listing & ulasan ─────────────────────────────────
CREATE TABLE IF NOT EXISTS reports (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER NOT NULL,
    listing_id  INTEGER NULL,      -- NULL bila laporan menyorot ulasan saja
    review_id   INTEGER NULL,      -- laporan atas ulasan (FK reviews)
    reason      VARCHAR(255) NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','resolved','rejected')),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_report_review UNIQUE (reporter_id, review_id),
    CONSTRAINT fk_report_user    FOREIGN KEY (reporter_id) REFERENCES users(id)   ON DELETE CASCADE,
    CONSTRAINT fk_report_listing FOREIGN KEY (listing_id)  REFERENCES listings(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_review  FOREIGN KEY (review_id)   REFERENCES reviews(id)  ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_report_status ON reports (status);
CREATE INDEX IF NOT EXISTS fk_report_listing ON reports (listing_id);
CREATE INDEX IF NOT EXISTS fk_report_review ON reports (review_id);

-- ── Pengaturan situs ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
    key    VARCHAR(60) PRIMARY KEY,
    value  TEXT NOT NULL
);

-- ============================================================
-- Seed (idempotent — aman dijalankan berulang)
-- ============================================================

INSERT INTO categories (name, slug, type) VALUES
    ('Jasa Web',                'jasa-web',               'service'),
    ('Elektronik',              'elektronik',             'product'),
    ('Fashion',                 'fashion',                'product'),
    ('Buku',                    'buku',                   'product'),
    ('Furnitur',                'furnitur',               'product'),
    ('Peralatan Rumah Tangga',  'peralatan-rumah-tangga', 'product'),
    ('Hobi',                    'hobi',                   'product'),
    ('Kendaraan',               'kendaraan',              'product'),
    ('Aksesoris',               'aksesoris',              'product'),
    ('Lainnya',                 'lainnya',                'all')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO settings (key, value) VALUES
    ('payment_wa',           '6287867851779'),
    ('payment_qris',         'assets/img/qr.jpeg'),
    ('payment_ewallet_num',  '0878-6785-1779'),
    ('payment_ewallet_name', 'SESSIONS STUDIO'),
    ('payment_bca',          '1234567890'),
    ('payment_bni',          '0987654321'),
    ('payment_bri',          '1122334455'),
    ('payment_bank_name',    'a.n. Nama Kamu')
ON CONFLICT (key) DO NOTHING;

-- Subtipe per kategori
INSERT INTO listing_subtypes (category_id, name, slug)
SELECT c.id, v.name, v.slug
FROM (VALUES
    ('kendaraan','Sepeda','sepeda'),  ('kendaraan','Motor','motor'),
    ('kendaraan','Mobil','mobil'),    ('kendaraan','Bajaj','bajaj'),
    ('kendaraan','Pesawat','pesawat'),('kendaraan','Kapal','kapal'),
    ('elektronik','Handphone','handphone'), ('elektronik','Laptop','laptop'),
    ('elektronik','Kamera','kamera'), ('elektronik','Televisi','televisi'),
    ('elektronik','Audio','audio'),
    ('buku','Novel','novel'), ('buku','Komik','komik'),
    ('buku','Buku Pelajaran','buku-pelajaran'), ('buku','Majalah','majalah'),
    ('furnitur','Meja','meja'), ('furnitur','Kursi','kursi'),
    ('furnitur','Lemari','lemari'), ('furnitur','Kasur','kasur')
) AS v(cat_slug, name, slug)
JOIN categories c ON c.slug = v.cat_slug
ON CONFLICT (category_id, slug) DO NOTHING;

-- Merek per subtipe
INSERT INTO listing_brands (subtype_id, name, slug)
SELECT s.id, v.name, v.slug
FROM (VALUES
    ('Sepeda','Polygon','polygon'), ('Sepeda','United','united'),
    ('Sepeda','Wim Cycle','wim-cycle'), ('Sepeda','Federal','federal'),
    ('Motor','Honda','honda'), ('Motor','Yamaha','yamaha'),
    ('Motor','Suzuki','suzuki'), ('Motor','Kawasaki','kawasaki'),
    ('Mobil','Toyota','toyota'), ('Mobil','Daihatsu','daihatsu'),
    ('Mobil','Mitsubishi','mitsubishi'), ('Mobil','Honda','honda'),
    ('Mobil','Suzuki','suzuki'), ('Mobil','Hyundai','hyundai'),
    ('Handphone','Samsung','samsung'), ('Handphone','Apple','apple'),
    ('Handphone','Xiaomi','xiaomi'), ('Handphone','Oppo','oppo'),
    ('Handphone','Vivo','vivo'),
    ('Laptop','Asus','asus'), ('Laptop','Acer','acer'),
    ('Laptop','Lenovo','lenovo'), ('Laptop','Apple','apple'),
    ('Laptop','HP','hp'),
    ('Kamera','Canon','canon'), ('Kamera','Nikon','nikon'),
    ('Kamera','Sony','sony'), ('Kamera','Fujifilm','fujifilm'),
    ('Televisi','Samsung','samsung'), ('Televisi','LG','lg'),
    ('Televisi','Sony','sony'), ('Televisi','TCL','tcl'),
    ('Audio','Sony','sony'), ('Audio','JBL','jbl'),
    ('Audio','Sennheiser','sennheiser')
) AS v(sub_name, name, slug)
JOIN listing_subtypes s ON s.name = v.sub_name
ON CONFLICT (subtype_id, slug) DO NOTHING;

-- ⚠️ Akun admin TIDAK dibuat di sini. Jalankan:
--    php database/migrate.php --seed-admin
-- Password di-generate acak lalu ditampilkan sekali, atau set via env:
--    SESSIONS_ADMIN_PASSWORD='...' php database/migrate.php --seed-admin
